// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDILnPySItIiLp8xmubGIg0RV7IfCj320Q',
    appId: '1:130996671558:web:e42772f00073ddf4caa647',
    messagingSenderId: '130996671558',
    projectId: 'unimatchempresassdk',
    authDomain: 'unimatchempresassdk.firebaseapp.com',
    storageBucket: 'unimatchempresassdk.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWXWjZCjgxV7aN6VrhQrH1FvCF7XJR_Ro',
    appId: '1:130996671558:android:b6c93ae013a271bacaa647',
    messagingSenderId: '130996671558',
    projectId: 'unimatchempresassdk',
    storageBucket: 'unimatchempresassdk.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAQzNA4R7LaxgDA4Ls-wtLlSnMhvuHnSc',
    appId: '1:130996671558:ios:34608ce57396f6a8caa647',
    messagingSenderId: '130996671558',
    projectId: 'unimatchempresassdk',
    storageBucket: 'unimatchempresassdk.firebasestorage.app',
    iosBundleId: 'com.example.unimatchEmpresas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAQzNA4R7LaxgDA4Ls-wtLlSnMhvuHnSc',
    appId: '1:130996671558:ios:34608ce57396f6a8caa647',
    messagingSenderId: '130996671558',
    projectId: 'unimatchempresassdk',
    storageBucket: 'unimatchempresassdk.firebasestorage.app',
    iosBundleId: 'com.example.unimatchEmpresas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDILnPySItIiLp8xmubGIg0RV7IfCj320Q',
    appId: '1:130996671558:web:38b52b0181e36a34caa647',
    messagingSenderId: '130996671558',
    projectId: 'unimatchempresassdk',
    authDomain: 'unimatchempresassdk.firebaseapp.com',
    storageBucket: 'unimatchempresassdk.firebasestorage.app',
  );

}