// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoKh7jm9Xk74Z79qNJFR7T6YJHGzT4Cmk',
    appId: '1:782590916368:web:ca72891eb44ebb88411795',
    messagingSenderId: '782590916368',
    projectId: 'unimatchempresas',
    authDomain: 'unimatchempresas.firebaseapp.com',
    storageBucket: 'unimatchempresas.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhsgXwLpnDP2rpcbn7MhYXUMV4tZ-pV40',
    appId: '1:782590916368:android:dec5d324b450a227411795',
    messagingSenderId: '782590916368',
    projectId: 'unimatchempresas',
    storageBucket: 'unimatchempresas.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1SiRTclf_1p7ohtsLLL7XEdwEMbnd3s4',
    appId: '1:782590916368:ios:cdde5f1d766fad35411795',
    messagingSenderId: '782590916368',
    projectId: 'unimatchempresas',
    storageBucket: 'unimatchempresas.firebasestorage.app',
    iosBundleId: 'com.example.unimatchEmpresas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1SiRTclf_1p7ohtsLLL7XEdwEMbnd3s4',
    appId: '1:782590916368:ios:cdde5f1d766fad35411795',
    messagingSenderId: '782590916368',
    projectId: 'unimatchempresas',
    storageBucket: 'unimatchempresas.firebasestorage.app',
    iosBundleId: 'com.example.unimatchEmpresas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoKh7jm9Xk74Z79qNJFR7T6YJHGzT4Cmk',
    appId: '1:782590916368:web:bed2fa161d6e1474411795',
    messagingSenderId: '782590916368',
    projectId: 'unimatchempresas',
    authDomain: 'unimatchempresas.firebaseapp.com',
    storageBucket: 'unimatchempresas.firebasestorage.app',
  );
}
